class Autogenerated {
  List<Predictions>? predictions;
  String? status;


  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['predictions'] != null) {
      predictions = <Predictions>[];
      json['predictions'].forEach((v) {
        predictions!.add(new Predictions.fromJson(v));
      });
    }
    status = json['status'];
  }

}

class Predictions {
  String? description;
  String? placeId;


  Predictions.fromJson(Map<String, dynamic> json) {
    description = json['description'];
    placeId = json['place_id'];
  }
}

//https://developers.google.com/maps/documentation/places/web-service/autocomplete
//https://developers.google.com/maps/documentation/places/web-service/details